name : Deployment


on:
  push:
    branches:
      - main

env:
  FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

jobs:
  deploy:
    name: GitHub Pages
    runs-on : ubuntu-latest

    steps:
      - name : Checkout
        uses: actions/checkout@v2

      - name : Install Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '12'

      - name : Install packages
        run: npm i

      - name: Create firebaseconfig.js
        run: echo $FIREBASE_CONFIG | base64 --decode > ./src/firebaseconfig.js

      - name: Build
        run: npm run build
        env:
          CI: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build